/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diferent;

/**
 *
 * @author Marc
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        diferent = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        aplicaciones = new javax.swing.JMenu();
        Calculadora = new javax.swing.JMenuItem();
        reloj = new javax.swing.JMenuItem();
        juegos = new javax.swing.JMenu();
        bloques = new javax.swing.JMenuItem();
        tetris = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        diferent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sistema (1).png"))); // NOI18N
        diferent.setText("<Diferent>");

        salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit (1).png"))); // NOI18N
        salir.setText("Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        diferent.add(salir);

        jMenuBar1.add(diferent);

        aplicaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aplic (1).png"))); // NOI18N
        aplicaciones.setText("Aplicaciones");

        Calculadora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Calculadora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Calculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icono_calculadora (1).jpg"))); // NOI18N
        Calculadora.setText("Calculadora");
        Calculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculadoraActionPerformed(evt);
            }
        });
        aplicaciones.add(Calculadora);

        reloj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        reloj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reloj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reloj (1).png"))); // NOI18N
        reloj.setText("Reloj");
        reloj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relojActionPerformed(evt);
            }
        });
        aplicaciones.add(reloj);

        jMenuBar1.add(aplicaciones);

        juegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/juegos (1).png"))); // NOI18N
        juegos.setText("Juegos");

        bloques.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bloques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bloques (1).png"))); // NOI18N
        bloques.setText("Bloques");
        bloques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquesActionPerformed(evt);
            }
        });
        juegos.add(bloques);

        tetris.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tetris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tetris (1).png"))); // NOI18N
        tetris.setText("Tetris");
        tetris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tetrisActionPerformed(evt);
            }
        });
        juegos.add(tetris);

        jMenuBar1.add(juegos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculadoraActionPerformed
        // Al seleccionar la calculadora:
        Calculadora cald = new Calculadora();
        escritorio.add(cald);
        cald.show();
    }//GEN-LAST:event_CalculadoraActionPerformed

    private void relojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relojActionPerformed
        // Al seleccionar el reloj:
        Reloj rel = new Reloj();
        escritorio.add(rel);
        rel.show();
    }//GEN-LAST:event_relojActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // Al clickar salir:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void bloquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquesActionPerformed
        // Al pulsar bloques:
        raketa play = new raketa();
        escritorio.add(play);
        play.show();
    }//GEN-LAST:event_bloquesActionPerformed

    private void tetrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tetrisActionPerformed
        // Al pulsar tetris:
        Tetris tet = new Tetris();
        escritorio.add(tet);
        tet.show();
    }//GEN-LAST:event_tetrisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Calculadora;
    private javax.swing.JMenu aplicaciones;
    private javax.swing.JMenuItem bloques;
    private javax.swing.JMenu diferent;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu juegos;
    private javax.swing.JMenuItem reloj;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem tetris;
    // End of variables declaration//GEN-END:variables
}
